services:
  postgres:
    image: postgres:17-alpine
    container_name: grand-oral-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: grandoral
      POSTGRES_PASSWORD: grandoral
      POSTGRES_DB: grandoral
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
